"""SR26 project management tabs, adapted from the SR25 master's project tabs
(0 SR24 Development prep, 1 Project Plan, 1a Process improvement plan, 1./2 Timeline & RASCI,
3 To Do list - comms+web, 6 Content-contributor checklist, 3d SR23 Page index).

Content is drawn from the 2026 Sustainability reporting approach (DRAFT Sep 2026). Dates are indicative.
"""
from datetime import date, timedelta

from openpyxl.formatting.rule import CellIsRule
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


def project_tabs(wb):
    import build as B  # style helpers

    def kv_sheet(name, subtitle, sections, colw=110):
        ws = wb.create_sheet(name)
        B.title(ws, "2026 Sustainability Report", subtitle)
        r = 4
        for head, rows in sections:
            ws.cell(r, 2, head).font = Font(name="Aptos", bold=True, size=14, color=B.NAVY)
            r += 1
            for k, v in rows:
                a = ws.cell(r, 2, k); a.fill = B.HDR; a.font = Font(name="Aptos", bold=True, color="FFFFFF"); a.alignment = B.WRAP; a.border = B.BOX
                c = ws.cell(r, 3, v); c.alignment = B.WRAP; c.border = B.BOX; c.font = Font(name="Aptos")
                ws.row_dimensions[r].height = max(20, 15 * (v.count("\n") + 1 + len(v) // 120))
                r += 1
            r += 1
        B.widths(ws, {"A": 4, "B": 26, "C": colw})
        return ws

    # ---------------- P0 Project overview (SR24 Development prep + 1a Process improvement plan)
    kv_sheet("P0 Project overview", "P0. Project overview", [
        ("1. Purpose", [
            ("This workbook", "Single working file for SR26 data collection and project delivery: requirements, requests, responses, scoring, evidence, plus project plan, timeline, comms/web to-do list and content-contributor checklist (P-tabs)."),
            ("SR26 in one line", "Transition-year report covering CY2026: distinguish activity under the former Sustainability Plan 2030 from foundations and early actions after the Sustainability 2030 launch (~20 Oct 2026 TBC). No published traffic lights in 2026."),
        ]),
        ("2. Lessons from SR25 and actions for SR26", [
            ("Keep tailored data requests", "SR25 streamlined requests achieved a 100% response rate → keep targeted, faculty-specific requests (see Request wording log); avoid complex requests."),
            ("Keep independent senior review", "Retain Target Status Review Group as the Sustainability Reporting Review Group (~15 Feb 2027)."),
            ("Strengthen data controls", "Central Evidence register, data owner confirmation (columns Q–R on every request), data source records, Databook alignment."),
            ("Integrate with Annual Report", "Engage Annual Report team in October; shared dependency map; late operational data (Feb–Mar) on a later pathway."),
            ("Agree comms roles early", "RASCI with Strategic Communications, comms, digital and design at project start (P2)."),
            ("Plan web and close from the outset", "Year-specific report URL, central landing page, analytics measures agreed before launch, formal retrospective (P3, P2)."),
            ("Simpler project management", "This simplified tracker; induction walkthrough; direct messages for assigned tasks, group channel for shared updates; blocker escalation as a standing meeting item."),
            ("Follow up non-approval", "SR25: FBE filled in the template but did not approve; Science disagreed with metrics → track 'Owner confirmed' in the Request tracker and chase; offer January support meetings."),
        ]),
        ("3. How to use this workbook", [
            ("Records management", "Save on the Sustainability Strategy Team SharePoint (Sustainability report 2026 > Report development). One document owner per working file; notify collaborators when a new version is saved. Avoid extra sub-folders in the data folder."),
            ("Responses", "Paste returned responses into the Faculties / central-unit tabs without inserting rows inside a block (A1/0.5/T2 formulas look up by Ref)."),
            ("Regenerating", "Templates are generated by build.py – update settings there to add faculties/units, then re-run."),
        ]),
        ("4. Key reference documents", [
            ("SR26 approach", "2026 Sustainability reporting approach & target status assessment framework – DRAFT Sep 2026"),
            ("SR25 documents", "SR25 Reporting framework (Jan 2026); Faculty/portfolio engagement plan and comms 2025-26; 2025 end-year reporting master spreadsheet V0.2; Target status review process doc (Jan 2026); Target status assessment (final 18.3.26); SR25 Final (Word); SR25 Project close report and key lessons learnt"),
            ("Targets", "Sustainability 2030 Updated Targets (Not for distribution) – Qual and Quan worksheets"),
        ]),
        ("5. Team processes", [
            ("Meetings", "Weekly production meeting (SST + comms/design); standing items: progress, blockers/escalation, decisions."),
            ("Communication", "Direct messages for individual tasks; group channel for shared updates."),
        ]),
    ])

    # ---------------- P1 Project plan on a page
    kv_sheet("P1 Project plan", "P1. SR26 Project plan on a page", [
        ("Project plan on a page", [
            ("Version control", f"DRAFT {B.VERSION} – based on SR26 approach (Sep 2026)"),
            ("Context", "The annual Sustainability Report is the University's core public account of sustainability progress. SR26 is a transition report following the refreshed Sustainability 2030 launch (~20 Oct 2026)."),
            ("Objectives / principles", "Accurate and transparent (clear transition-year framing) • Fit-for-purpose (request only what is necessary, available and usable) • Evidence-led (each request linked to an indicator, report use and evidence) • Integrated (Databook is the primary quantitative source) • Reusable (templates and roles for 2027+) • Accessible (one web page per priority area: narrative + case studies) • Credible (independent review; traffic-light ratings deferred to 2027 reporting)"),
            ("Reporting model", "Webpages by priority area; transition-year framing; no published traffic lights (internal ratings only); Databook for quantitative data; targeted qualitative requests; early case-study pipeline; Sustainability Reporting Review Group."),
            ("Workstreams", "Governance • Data collection & analysis (this workbook) • Content development • Communications & web build"),
            ("Key stakeholders", f"Director, Sustainability (decision owner) • COO • VCAG • University Executive • University Council • Investment Management Committee • Sustainability Reporting Review Group • Associate Deans Sustainability • Priority-area working groups • Central data owners ({', '.join(c[0] for c in B.CENTRAL)}) • Strategic Communications, digital & design • University Annual Report team"),
            ("Phases", "Sep–Oct 2026 Set-up • Oct 2026 Process design & launch • Nov–Dec 2026 Evidence collection • Jan 2027 Drafting & validation • Feb–May 2027 Review & governance • May–Jun 2027 Publication & close-out"),
            ("Outputs", "Requirements matrix • Request templates • Evidence register • Case-study pipeline • Draft report & issues paper • VCAG/UE/Council papers • Report website • Retrospective"),
            ("Success measures", "Response rate • Reporting burden • Project effort • Data-quality issues • Web sessions, users and views • Stakeholder feedback"),
        ]),
        ("Key risks and controls", [
            ("Full-year implication", "Report implies a full year of progress against targets launched 20 Oct → explicit transition-year framing."),
            ("Onerous requests", "Requests onerous or non-comparable → necessity and usability test; pilot templates; don't ask for data areas can't hold."),
            ("Databook overlap", "Databook and narrative requests overlap/conflict → one requirements matrix and evidence register; one source of truth per indicator."),
            ("New working groups", "Asked to evidence delivery before established → maturity-based 2026 request."),
            ("Case studies dominate", "→ selection criteria: relevance, evidence, outcome, transferability, balance, permission."),
            ("Late responses", "→ issue requirements early, support meetings, senior sponsorship, escalate gaps."),
            ("Review group role", "Unclear without traffic lights → approve review criteria and decision rights in advance."),
            ("Annual Report divergence", "→ engage in October; shared dependency/data map; reconcile shared figures."),
        ]),
        ("Decisions required (from SR26 approach)", [
            ("1. Transition-year model", "Director, Sustainability – Approved (internal traffic lights: sub-decision)"),
            ("2. Evidence & engagement model", "Director, Sustainability – Pending (awaiting Stefanus' WIP)"),
            ("3. Assurance & governance pathway", "Director, Sustainability – Closed"),
            ("4. Modern slavery timeline alignment", "Director, Sustainability (and Head of Procurement) – Open, watch item"),
        ]),
    ])

    # ---------------- P2 Timeline, RASCI & task register (Gantt)
    ws = wb.create_sheet("P2 Timeline & RASCI")
    B.title(ws, "2026 Sustainability Report", "P2. Timeline, RASCI & task register")
    ws["B3"] = "Indicative dates from the SR26 approach – confirm governance dates with governance offices. Gantt bars fill automatically from Start/End."
    ws["B3"].font = Font(name="Aptos", italic=True)
    D = date
    tasks = [
        ("Project set-up (Sep–Oct 2026)", None),
        ("Confirm scope, reporting model, governance pathway and decisions", "Decision log", D(2026, 9, 14), D(2026, 10, 16), "SST", "Director, Sustainability", "", "VCAG (I)", "High"),
        ("Project charter, schedule, RASCI, decision log, issues register", "Approved by Oct", D(2026, 9, 28), D(2026, 10, 23), "SST", "Director, Sustainability", "", "Comms, design", "High"),
        ("Map refreshed targets/indicators to Databook, systems, owners", "Requirements matrix", D(2026, 9, 21), D(2026, 10, 16), "Stefanus", "Gerard Healey", "Rose", "Data owners", "High"),
        ("Confirm stakeholder structure (CGOP/CDEP/CDSS) and owners (Gerard: resilience, estate)", "Stakeholder map", D(2026, 10, 5), D(2026, 10, 16), "Stefanus", "Gerard Healey", "", "", "High"),
        ("Test request templates (ABP walkthrough) and Teams workbook links", "Templates and links tested", D(2026, 10, 12), D(2026, 10, 30), "Stefanus", "Gerard Healey", "", "ADs Sustainability", "High"),
        ("Approve Review Group criteria, decision rights, escalation pathway", "Before collection", D(2026, 10, 5), D(2026, 10, 30), "SST", "Director, Sustainability", "", "Review Group", "Medium"),
        ("Process design & launch (Oct 2026)", None),
        ("Finalise templates and evidence register", "Templates final", D(2026, 10, 19), D(2026, 10, 30), "Stefanus", "Gerard Healey", "", "", "High"),
        ("Coordinate with University Annual Report team (dependency map)", "Shared data map", D(2026, 10, 5), D(2026, 10, 30), "SST", "Director, Sustainability", "", "Annual Report team", "High"),
        ("Convene Strategic Comms, digital & design; agree comms RASCI", "Kick-off", D(2026, 10, 5), D(2026, 10, 23), "SST", "Director, Sustainability", "Strategic Comms", "Design, digital", "High"),
        ("Sustainability 2030 launch", "~20 Oct (TBC)", D(2026, 10, 20), D(2026, 10, 20), "", "", "", "", "Milestone"),
        ("Brief contributor groups / working groups (after launch)", "", D(2026, 10, 20), D(2026, 11, 6), "SST", "", "", "Working groups", "Medium"),
        ("Joint ADs Sustainability & ADs T&L session", "Structured prompt in advance", D(2026, 10, 19), D(2026, 10, 30), "SST", "", "", "ADs", "Medium"),
        ("Early engagement: socialise requirements in existing meetings (esp. education-related)", "Stakeholder awareness", D(2026, 10, 26), D(2026, 10, 30), "SST", "", "", "Faculties, central units", "High"),
        ("Collection & evidence (Nov–Dec 2026)", None),
        ("Collection launch: issue tailored requests (separate workbook per faculty/unit)", "Requests formally issued", D(2026, 11, 2), D(2026, 11, 6), "SST", "Director, Sustainability", "COO (sponsor)", "", "High"),
        ("Collection period: stakeholders prepare responses and evidence", "Initial submission", D(2026, 11, 2), D(2026, 12, 15), "Faculties, central units", "", "SST", "", "High"),
        ("CDSS answers questions and records clarifications centrally", "Clarifications log", D(2026, 11, 2), D(2026, 12, 15), "CDSS", "", "", "", "Medium"),
        ("Optional 1:1 meetings (on request)", "", D(2026, 11, 2), D(2026, 12, 15), "SST", "", "", "Data owners", "Medium"),
        ("Responses and highlighted stories due", "15 Dec", D(2026, 12, 15), D(2026, 12, 15), "", "", "", "", "Milestone"),
        ("First review: completeness and evidence quality", "First QA assessment", D(2026, 12, 14), D(2026, 12, 18), "SST", "", "", "", "High"),
        ("Targeted follow-up where evidence is incomplete, ambiguous or missing (no second broad request; ask availability)", "Resolved gaps", D(2026, 12, 14), D(2026, 12, 24), "SST", "", "", "Data owners", "High"),
        ("Consolidation: finalise master, identify unresolved gaps, prepare drafting material", "Consolidated master spreadsheet", D(2026, 12, 21), D(2026, 12, 24), "SST", "Director, Sustainability", "", "", "High"),
        ("Drafting & data validation (Jan 2027)", None),
        ("Commence drafting from consolidated master", "", D(2027, 1, 4), D(2027, 2, 5), "SST", "", "", "", "High"),
        ("Confirm final quantitative figures (Databook)", "", D(2027, 1, 4), D(2027, 1, 29), "SST", "", "Data owners", "", "High"),
        ("Review responses by indicator (A1 / T1 / T2) – no target status rating in 2026", "", D(2027, 1, 18), D(2027, 2, 5), "Rose (TBC)", "Director, Sustainability", "SST", "", "High"),
        ("Full draft + issues paper; close evidence gaps", "", D(2027, 1, 11), D(2027, 2, 5), "SST", "Director, Sustainability", "", "", "High"),
        ("Review & governance (Feb–May 2027)", None),
        ("VCAG papers due (Review Group findings)", "10 Feb", D(2027, 2, 10), D(2027, 2, 10), "SST", "Director, Sustainability", "", "", "Milestone"),
        ("Sustainability Reporting Review Group", "~15 Feb (8–10 Feb TBC)", D(2027, 2, 8), D(2027, 2, 15), "Rose (convenor, TBC)", "", "", "", "Milestone"),
        ("VCAG – notes Review Group findings", "16 Feb", D(2027, 2, 16), D(2027, 2, 16), "", "", "", "", "Milestone"),
        ("Investment Management Committee – Responsible Investments section", "~25 Feb (papers ~18 Feb)", D(2027, 2, 18), D(2027, 2, 25), "SST", "", "", "", "Milestone"),
        ("Full-report finalisation; Strategic Comms review; reconcile Annual Report data", "", D(2027, 2, 16), D(2027, 2, 26), "SST", "", "Strategic Comms", "", "High"),
        ("VCAG – notes full report", "~2 Mar (papers ~25 Feb)", D(2027, 3, 2), D(2027, 3, 2), "", "", "", "", "Milestone"),
        ("University Executive – notes report", "~25 Mar (papers ~12 Mar)", D(2027, 3, 25), D(2027, 3, 25), "", "", "", "", "Milestone"),
        ("University Council – approves report", "~6 May (papers ~10 Apr)", D(2027, 5, 6), D(2027, 5, 6), "", "", "", "", "Milestone"),
        ("Publication & close-out (May–Jun 2027)", None),
        ("Web build; QA, accessibility and web checks; agree analytics measures", "Before launch", D(2027, 3, 1), D(2027, 5, 28), "Comms/digital", "", "SST", "", "High"),
        ("Publish report (year-specific URL + landing page)", "June", D(2027, 6, 1), D(2027, 6, 30), "Comms/digital", "Director, Sustainability", "", "", "Milestone"),
        ("Monitor engagement; project retrospective; improvements for 2027 cycle", "", D(2027, 6, 1), D(2027, 7, 30), "SST", "", "Comms, design", "", "Medium"),
    ]
    cols = ["Phase / key activity", "Key milestone", "Start", "End", "R", "A", "S", "C/I", "Priority", "Status"]
    hr = 9
    B.hdr_row(ws, hr, cols)
    start = date(2026, 9, 7)
    weeks = [start + timedelta(weeks=i) for i in range(48)]
    for i, w in enumerate(weeks):
        c = ws.cell(hr, 12 + i, w); c.number_format = "d-mmm"; c.fill = B.HDR
        c.font = Font(name="Aptos", size=8, bold=True, color="FFFFFF"); c.alignment = Alignment(text_rotation=90, horizontal="center")
        m = ws.cell(hr - 1, 12 + i, w.strftime("%b") if i == 0 or w.month != weeks[i - 1].month else "")
        m.font = Font(name="Aptos", bold=True)
        ws.column_dimensions[get_column_letter(12 + i)].width = 3.2
    r = hr + 1
    for t in tasks:
        if t[1] is None:
            c = ws.cell(r, 2, t[0]); c.font = Font(name="Aptos", bold=True, color="FFFFFF"); c.fill = PatternFill("solid", fgColor="156082")
            for cc in range(3, 12 + len(weeks)):
                ws.cell(r, cc).fill = PatternFill("solid", fgColor="156082")
        else:
            name, ms, s0, e0, R, A, S, CI, pr = t
            vals = [name, ms, s0, e0, R, A, S, CI, pr, "Not yet started"]
            for i, v in enumerate(vals):
                c = ws.cell(r, 2 + i, v); B.body(c)
                if i in (2, 3):
                    c.number_format = "dd/mm/yyyy"
            for i in range(len(weeks)):
                col = get_column_letter(12 + i)
                ws.cell(r, 12 + i, f'=IF(AND({col}${hr}+6>=$D{r},{col}${hr}<=$E{r}),1,"")')
        r += 1
    last = r - 1
    rng = f"L{hr + 1}:{get_column_letter(11 + len(weeks))}{last}"
    ws.conditional_formatting.add(rng, CellIsRule(operator="equal", formula=["1"], fill=PatternFill("solid", fgColor="FFC000"), font=Font(color="FFC000")))
    B.dv_list(ws, '"Not yet started,In progress,Complete,On hold,N/A"', f"K{hr + 1}:K{last}")
    B.widths(ws, {"A": 4, "B": 52, "C": 22, "D": 11, "E": 11, "F": 14, "G": 16, "H": 12, "I": 14, "J": 10, "K": 14})
    ws.freeze_panes = f"D{hr + 1}"
    # today marker
    ws.conditional_formatting.add(f"L{hr}:{get_column_letter(11 + len(weeks))}{hr}",
                                  CellIsRule(operator="between", formula=["TODAY()-6", "TODAY()"], fill=PatternFill("solid", fgColor="C00000")))

    # ---------------- P3 To do list – comms + web
    ws = wb.create_sheet("P3 To do – comms+web")
    B.title(ws, "2026 Sustainability Report", "P3. Comms + web build to-do list")
    ws["B4"] = "Track comms, web build and design tasks. Priority: Low / Medium / High / Urgent."
    cols = ["Report component or page", "Case study/content name", "Lead", "Priority level", "Agreed deadline", "Action needed", "Details",
            "Complete? (Y/N)", "Updates/blockers/FYI"]
    B.hdr_row(ws, 6, cols)
    seed = [
        ("Web – whole report", "Year-specific report URL", "Comms/digital", "High", "", "Set up", "Use a year-specific URL (e.g. /sustainabilityreport/2026) and retain the central reports landing page (SR25 lesson)."),
        ("Web – whole report", "Analytics measures", "Comms/digital", "High", "", "Agree before launch", "Agree web sessions, users and views measures before launch so project close can report them."),
        ("Web – whole report", "Accessibility & reviewer workflow testing", "Comms/digital", "High", "", "Test", "Navigation, links, mobile usability, accessibility, reviewer workflows – before governance approval."),
        ("Report introduction", "Transition-year framing", "SST", "High", "", "Draft", "Explain former SP2030 vs Sustainability 2030 (launched ~20 Oct 2026)."),
        ("Whole report", "Whole-report review", "Strategic Comms", "High", "", "Schedule", "Schedule early enough for material changes."),
    ]
    for k, v in enumerate(seed):
        for i in range(len(cols)):
            B.body(ws.cell(7 + k, 2 + i, v[i] if i < len(v) else ""))
    for rr in range(7 + len(seed), 60):
        for i in range(len(cols)):
            B.body(ws.cell(rr, 2 + i))
    B.dv_list(ws, '"Low,Medium,High,Urgent"', "E7:E59")
    B.dv_list(ws, '"Y,N"', "I7:I59")
    B.widths(ws, {"A": 4, "B": 26, "C": 30, "D": 14, "E": 12, "F": 14, "G": 20, "H": 50, "I": 11, "J": 36})

    # ---------------- P4 Content-contributor checklist
    ws = wb.create_sheet("P4 Content checklist")
    B.title(ws, "2026 Sustainability Report", "P4. Content contributor checklist")
    ws["B4"] = "Stakeholder management for report content: review by contributors, images, credits and captions, post-launch follow-up."
    cols = ["Report section", "Case study", "Activity areas", "Review required? (Y/N)", "Content contributors", "Project team liaison",
            "Sent for review (date)", "Changes required? (Y/N)", "SR26 draft updated? (Y/N)", "SR26 website updated? (Y/N)",
            "Images shared? (Y/N)", "Image URL", "Known image gap", "Credit noted?", "Caption text", "Permission to publish confirmed?",
            "Post-launch: send to", "CC", "Sent (date)", "Complete? (Y/N)"]
    B.hdr_row(ws, 6, cols)
    pas = ["Exceptional education", "Transformational research", "Climate leadership", "Nature and biodiversity", "Responsible AI",
           "Estate and infrastructure", "Circular economy", "Responsible procurement", "Modern slavery and human rights",
           "Responsible investments", "Enablers"]
    for k in range(60):
        for i in range(len(cols)):
            B.body(ws.cell(7 + k, 2 + i))
    # list kept on the Lists sheet: an inline list over 255 characters stops Excel opening the file
    sections = ["Report introduction", "Our impact"] + pas
    lst = wb["Lists"]; lst["K1"] = "Report section"
    for i, v in enumerate(sections):
        lst.cell(2 + i, 11, v)
    B.dv_list(ws, f"=Lists!$K$2:$K${1 + len(sections)}", "B7:B66")
    for col in "EIJKLQU":
        B.dv_list(ws, '"Y,N"', f"{col}7:{col}66")
    B.widths(ws, {"A": 4, "B": 24, "C": 34, "D": 18})
    for i in range(3, len(cols)):
        ws.column_dimensions[get_column_letter(2 + i)].width = 14
    ws.freeze_panes = "D7"

    # ---------------- P5 SR26 page index
    ws = wb.create_sheet("P5 SR26 page index")
    B.title(ws, "2026 Sustainability Report", "P5. SR26 page index (URLs)")
    cols = ["Ref", "Sustainability 2030 component", "Page name", "Story / case study", "SR26 link", "Page description", "Character count", "SR25 equivalent page"]
    B.hdr_row(ws, 5, cols)
    rows = [("FM01", "N/A", "Landing page"), ("FM02", "N/A", "Overview (transition year)"), ("FM03", "N/A", "Our impact")]
    doms = {"Education and research": ["Exceptional education", "Transformational research"],
            "Sustainability leadership": ["Climate leadership", "Nature and biodiversity", "Responsible AI"],
            "Resilient University": ["Estate and infrastructure", "Circular economy", "Responsible procurement",
                                     "Modern slavery and human rights", "Responsible investments"],
            "Enablers": ["Enablers"]}
    n = 0
    for d, ps in doms.items():
        for pa in ps:
            n += 1
            rows.append((f"PA{n:02d}", d, pa))
    for k, v in enumerate(rows):
        rr = 6 + k
        for i in range(len(cols)):
            B.body(ws.cell(rr, 2 + i, v[i] if i < len(v) else ""), B.REFF if i == 0 else None)
        ws.cell(rr, 8, f"=LEN(G{rr})")
    B.widths(ws, {"A": 4, "B": 8, "C": 26, "D": 30, "E": 36, "F": 40, "G": 50, "H": 10, "I": 30})
